#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'irb'

basedir = File.expand_path('../..', __FILE__)
require File.join(basedir, 'lib', 'lint_fu')


module IRB # :nodoc:
  def self.start_session(binding)
    unless @__initialized
      args = ARGV
      ARGV.replace(ARGV.dup)
      IRB.setup(nil)
      ARGV.replace(args)
      @__initialized = true
    end

    workspace = WorkSpace.new(binding)

    irb = Irb.new(workspace)

    @CONF[:IRB_RC].call(irb.context) if @CONF[:IRB_RC]
    @CONF[:MAIN_CONTEXT] = irb.context

    catch(:IRB_EXIT) do
      irb.eval_input
    end
  end
end

puts '** Welcome to lint-fu debug console. Use this to play with lint-fu classes.'
puts '** The module has been included for your convenience, so you can access types'
puts '** without prepending LintFu:: to thir names. Have fun!'

include LintFu
IRB.start_session(binding)
